server:
   port: 8000

spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/C76-S3-lolshop
      username: root
      password: a
      driver-class-name: com.mysql.jdbc.Driver
   application:
      name: lolshop-index
   mail:
      #邮箱服务器地址
      host: smtp.qq.com
      #用户名
      username: 2507181643@qq.com
      #密码
      password: mnkliixyvtyvbeei
      # 编码
      default-encoding: UTF-8
#以谁来发送邮件 自定义的参数
mail:
   fromMail:        
      addr: 891588825@qq.com
      
mybatis:
   #实体类的路径
   type-aliases-package: com.yc.lolshop.bean
   configuration:
      map-under-score-to-camel-case: true
    
#日志配置
logging:
   level:
      com:
         yc:
            lolshop:
               dao: debug
               web: warn
#开启熔断 降级开关               
feign:
  hystrix:
    enabled: true

#   --spring.profiles.active=index-8003  
---
spring:
   profiles: index-8003
server:
   port: 8003   